codecov:
  notify:
    wait_for_ci: true
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default: false
      turtle-canon:
        threshold: 1%
        flags:
          - turtle-canon
    patch:
      default:
        threshold: 5%
    changes: false
