- id: turtle-canon
  name: Turtle Canon
  description: "Turtle Canon: A tool for canonizing Turtle (`.ttl`) ontology files."
  entry: turtle-canon
  language: python
  language_version: python3
  minimum_pre_commit_version: "1.15.0"
  require_serial: true
  files: \.ttl$
  types: [text]
