name: CI - Update accummulated dependencies PR

on:
  schedule:
    # At 8:30 every Wednesday (6:30 UTC)
    # Dependabot runs once a week (every Monday) (pip)
    # and every day (GH Actions) at 7:00 (5:00 UTC)
    - cron: "30 6 * * 3"
  workflow_dispatch:

jobs:
  create-collected-pr:
    name: External
    uses: SINTEF/ci-cd/.github/workflows/ci_update_dependencies.yml@v2.8.0
    if: github.repository_owner == 'CasperWA'
    with:
      # General
      git_username: "CasperWA"
      git_email: "casper.w.andersen@sintef.no"
      permanent_dependencies_branch: "ci/dependabot-updates"
      default_repo_branch: "main"
      pr_labels: "CI/CD,skip_changelog"
      extra_to_dos: "- [ ] Make sure that the PR is **squash** merged, with a sensible commit message."

      # Update pre-commit hooks
      update_pre-commit: true
      python_version: "3.10"
      install_extras: "[dev]"

    secrets:
      PAT: ${{ secrets.RELEASE_PAT }}
